In [1]:
#assi 6.1 Forward propagation

import numpy as np

def sigmoid(x):
  return 1/(1+np.exp(-x))

input_size = 3
hidden_size = 4
output_size = 2

w1 = np.random.randn(input_size,hidden_size).round()
b1 = np.random.randn(hidden_size).round()
w2 = np.random.randn(hidden_size,output_size).round()
b2 = np.random.randn(output_size).round()

x = np.array([[0.2,0.5,0.1]])

hidden_layer = sigmoid(np.dot(x,w1) + b1).round()
output_layer = sigmoid(np.dot(hidden_layer, w2) + b2).round()

print("weight 1 : ",w1)
print("weight 2 : ",w2)
print("bias 1 : ",b1)
print("bias 2 : ",b2)
print(output_layer)

weight 1 :  [[-0. -0. -1.  0.]
 [ 2.  1.  1. -1.]
 [ 0.  0.  2.  1.]]
weight 2 :  [[ 1.  0.]
 [-0.  1.]
 [ 0.  2.]
 [ 0. -0.]]
bias 1 :  [ 3. -0.  0. -0.]
bias 2 :  [-0.  1.]
[[1. 1.]]


In [4]:
# backpropGtion

from numpy import *

class NeuralNet(object):

  def __init__(self):
    random.seed(1)
    self.synaptic_weights = 2 * random.random((3, 1)) - 1

  def __sigmoid(self, x):
    return 1 / (1 + exp(-x))

  def __sigmoid_derivative(self, x):
    return x * (1 - x)

  def train(self, inputs, outputs, training_iteration):

    for iteration in range(training_iteration):
      output = self.learn(inputs)
      error = outputs - output
      adjustment = dot(inputs.T, error * self.__sigmoid_derivative(output))
      self.synaptic_weights += adjustment

  def learn(self, inputs):
    return self.__sigmoid(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":
  neural = NeuralNet()
  inputs = array([[0, 1, 1], [1, 0, 0], [1, 0, 1]])
  outputs = array([[1], [0], [1]])

  neural.train(inputs, outputs, 10000)
  print(neural.learn(array([1, 0, 1])))


[0.9897704]
